# -*- coding: utf-8 -*-
"""Calendar

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fBEQMSp0a7jZ6El_g3X3ZPHGqvJOQBwO
"""

class Calendar:
    def __init__(self):
        self.events = {}

    def add_event(self, date, event):   # add event to calendar for given date
        if date in self.events:
            self.events[date].append(event)  # if events exist, append the new event to the list of events for that date
        else:
            self.events[date] = [event]  # if events don't exist for the date, create a new list with the event

    def get_events(self, date): # get the list of events
        if date in self.events:  # if events exist on that day, return the sorted list for the date
            return sorted(self.events[date])
        else:
            return []  # if there are none, return an empty list

    def get_all_events(self):
        sorted_events = {}  # initialize an empty dictionary to store sorted events
        for date in sorted(self.events.keys()):  # go through the keys of the dictionary that are sorted
            sorted_events[date] = sorted(self.events[date])  # store the list of events
        return sorted_events


calendar = Calendar()

# add an event to the calendar
calendar.add_event("2/21/2024", "CS Midterm")

# get events for a specific date
print("Events for 2/21/2024:", calendar.get_events("2/21/2024"))
print("Events for 2/22/2024:", calendar.get_events("2/22/2024"))

# get all events in calendar
print("\nAll events:")
all_events = calendar.get_all_events()
for date, events in all_events.items():
    print(f"{date}: {events}")